name: twittueur
description: "Un projet de NSI pour créer un clone de Twitter en utilisant Flutter"
version: 1.0.0

environment:
  sdk: '>=3.3.0 <4.0.0'

flutter_native_splash:
  color: "#000000"
  image: assets/splash.png

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  expandable_text: 2.3.0
  flutter_dotenv: ^5.1.0 
  flutter_native_splash: ^2.4.0
  flutter_phoenix: ^1.1.1
  get_storage: ^2.1.1
  image_picker: ^1.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ 

